name: Update

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Run publish script
        run: |
          chmod +x ./scripts/publish-ombrac.sh
          ./scripts/publish-ombrac.sh

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet ombrac.rb || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if there are changes
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ombrac.rb
          git commit -m "chore: update to latest version"
          git push
